### ISSUE TITLE
Incorrect filesize for NextCloud?

### ISSUE THREAD

**Issue by hugoideler** [fsantini/KoboCloud#11]
- Nextcloud version: 15.0.11
- KoboCloud version: git HEAD on 2019-08-27
- Device: Kobo Forma

It seems that syncing from NextCloud does not work great: the files are reported as 9010 bytes while actually the files are much larger than that. It results in downloading of incorrect filesizes and therefore corrupt files on the Kobo. I've tried the Dropbox sync, and that works fine (for the same files).

```
2019-08-27_20:14:04 waiting for internet connection
Reading # Add your URLs to this file
Comment found
Reading # Remove the # from the following line to uninstall KoboCloud
Comment found
Reading #UNINSTALL
Comment found
Reading https://<REDACTED>
Getting https://<REDACTED>
<REDACTED>
<REDACTED>
https://<REDACTED>.....pdf -> /mnt/onboard/.kobo/kobocloud/Library/<REDACTED>.pdf
Remote size: 9010
getRemoteFile ended
Reading https://www.dropbox.com/sh/<REDACTED>
https://www.dropbox.com/sh/<REDACTED> -> /mnt/onboard/.kobo/kobocloud/Library/<REDACTED>.pdf
Remote size: 1696078
File exists: skipping
getRemoteFile ended
2019-08-27_20:14:18 done
```

**Comment by fsantini** [comment]
Hi! As I don't have my own installation of NextCloud, I opened a free account on owncube.com and tested the script. In my setup, the returned file size is correct. The fact that you actually have problems because of this is however strange, because the download itself should not take the remote size into account, this is only used to check for partial downloads, which should not happen regularly. Would you like to create a temporary test link with one file for me and send it privately, so I can investigate what is happening?

You can directly write to francesco.santini@gmail.com

**Comment by woutersj** [comment]
You may want to check the contents of the file with a text editor. I'm having the same issue. The files synced onto the device contain Nextcloud html instead of the intended content.
