### ISSUE TITLE
Problem downloading from Dropbox on Kobo Touch

### ISSUE THREAD

**Issue by remissao** [fsantini/KoboCloud#29]
Files are downloaded into .add/kobocloud/Library and don't show up in the ereader Menu.

Shouldn't the epubs be downloaded into the root folder?

**Comment by tylpk1216** [comment]
KoboCloud mounts .add/kobocloud/Library folder when running get.sh or udev_mount.sh.

You said your downloading was no problem. However you could not see these books.
I will guess the problem is here.
![mount](https://user-images.githubusercontent.com/14836065/86548803-4d290e00-bf70-11ea-8e34-2d35b7265965.png)

**Comment by groentebroer** [comment]
@remissao Could you check with the latest version?
