### ISSUE TITLE
Problem install (how to properly uninstall?)

### ISSUE THREAD

**Issue by therourke** [fsantini/KoboCloud#4]
It seems something has gone wrong with my installation. It is not syncing at all now (on my Kobo Clara HD).

My get.log file says this:

> 2018-11-27_17:28:01 waiting for internet connection
> Reading # Add your URLs to this file
> Comment found
> 2018-11-27_17:28:10 done

Which makes no sense, since my kobocloudrc file only contains the dropbox url, not that starting line from the template. It's like the installation is reading from a template version of the kobocloudrc file or something. 

I tried deleting the entire kobocloud directory - this gets recreated on reboot. I have also tried reinstalling the entire thing from scratch, but it makes no difference.

Any ideas what has happened? How can I do a full proper uninstall? Thanks

**Comment by fsantini** [comment]
Mmm... That's strange. At the moment unfortunately I don't have time to properly look into it, I'll try to check this and add an uninstall feature as soon as I can.

**Comment by fsantini** [comment]
I released a new version with uninstall support. Please flash the new KoboRoot.tgz to enable it. Afterwards, to have a clean slate again do the following:

1. Edit the .kobo/kobocloud/kobocloudrc file so that it contains the word UNINSTALL in capital on a line by itself (no spaces before or after)
2. Restart the kobo
3. Connect it to the network. Now the system files are deleted
4. Manually delete the .kobo/kobocloud directory in your kobo

Hope it works!
